name: web-action-process
env:
  APPLICATION_NAME : "keeper_web"
on: 
  push:
    branches: 
      - prod

jobs:
  Keeper-Web:
    runs-on: self-hosted
    
    steps:
      - name: PrintAppData
        run : |
          echo "Application name2: ${{ env.APPLICATION_NAME}}"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: 'false'